$(document).ready(function () {
	// variable to hold random number generated by start button
	var random = 0;

	// start button runs random number function
	$('#start').on('click', randomNumber);

	// listener for clicking on boxes to see if box id matches random number
	$('#blocksGoHere').on('click', '.block', rightWrong);

	//  array of colors for blocks
	var blockArray = ['#528CCB', '#F89406', '#F31D2F', '#FFF457', '#FF8600', '#00D717', '#2D3E50', '#A0B58D', '#7CEECE', '#EDD834', '#44BBFF', '#87E8C6', '#D1D5D8', '#E1FAFC', '#FF8F17'];

	// function run on start click to pick box id at random
	function randomNumber() {
		random = Math.floor(Math.random() * (1 + 15 - 0) + 0);
		$('.smallBlock').css('background-color', blockArray[random]);
		return random;
	}


	// iterates through array to give color and id to blocks and append them to div
	$.each(blockArray, function (i, val) {
		$('#blocksGoHere').append('<div class="block" id=' + i + '> </div>');
		$('#' + i).css('background-color', val);
		console.log(i);
		console.log(val);
	})

	// to determine if clicking on box matches the id chosen at random
	function rightWrong() {
		var $blockId = $(this).attr('id');
		parseInt($blockId);
		console.log($blockId);
		if ($blockId == random) {
			alert("You're Right");
		} else {
			alert("You're wrong!!");
		}
	}
});
